// Utah Muslim Businesses - Halal Marketplace Sample Data
// This data is used when the database is empty or not available

export const marketplaceCategories = [
  { id: '1', name: 'Restaurants & Food', slug: 'restaurants-food', icon: '🍽️', order: 1, active: true },
  { id: '2', name: 'Grocery & Halal Meat', slug: 'grocery-halal-meat', icon: '🥩', order: 2, active: true },
  { id: '3', name: 'Services', slug: 'services', icon: '🔧', order: 3, active: true },
  { id: '4', name: 'Education & Tutoring', slug: 'education-tutoring', icon: '📚', order: 4, active: true },
  { id: '5', name: 'Professional Services', slug: 'professional-services', icon: '💼', order: 5, active: true },
  { id: '6', name: 'Real Estate', slug: 'real-estate', icon: '🏠', order: 6, active: true },
];

export const marketplaceListings = [
  // FEATURED - Somali Restaurants
  {
    id: 'midnimo',
    title: 'Midnimo Somali Restaurant',
    slug: 'midnimo-somali-restaurant',
    description: 'Authentic Somali cuisine in the heart of Salt Lake City. Family-owned halal restaurant serving traditional home-style cooking. Famous for rice dishes, goat meat, and Somali tea.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Midnimo Restaurant',
    contactPhone: '(385) 227-8481',
    address: '55 N Redwood Rd',
    city: 'Salt Lake City',
    zipCode: '84116',
    status: 'approved',
    featured: true,
  },
  {
    id: 'horn-africa',
    title: 'Horn of Africa Restaurant',
    slug: 'horn-of-africa-restaurant',
    description: 'Traditional East African cuisine serving Somali, Ethiopian, and Eritrean dishes. Halal certified. Known for sambusas, suugo, and bariis.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Horn of Africa',
    contactPhone: '(801) 908-5498',
    address: '1320 S Swaner Rd',
    city: 'Salt Lake City',
    zipCode: '84104',
    status: 'approved',
    featured: true,
  },
  {
    id: 'jay-jay',
    title: 'Jay Jay Restaurant',
    slug: 'jay-jay-restaurant',
    description: 'Somali restaurant serving authentic halal cuisine. Traditional Somali dishes including rice, goat, chicken, and sambusas.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Jay Jay Restaurant',
    city: 'Salt Lake City',
    status: 'approved',
    featured: true,
  },

  // More Restaurants
  {
    id: 'shahrazad',
    title: 'Shahrazad Market & Restaurant',
    slug: 'shahrazad-market-restaurant',
    description: 'Locally owned Middle Eastern restaurant, marketplace, and Halal butcher shop. Serving authentic Mediterranean cuisine with fresh halal meats.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Shahrazad',
    contactPhone: '(801) 975-7635',
    address: '1615 W 2100 S',
    city: 'Salt Lake City',
    zipCode: '84119',
    status: 'approved',
    featured: false,
  },
  {
    id: 'shawarma-shack',
    title: 'Shawarma Shack',
    slug: 'shawarma-shack',
    description: 'Authentic shawarma and Middle Eastern favorites. All meat is 100% halal certified.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Shawarma Shack',
    contactPhone: '(801) 924-9700',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'curry-fried-chicken',
    title: 'Curry Fried Chicken',
    slug: 'curry-fried-chicken',
    description: 'Halal fried chicken with a South Asian twist. Crispy, flavorful, and 100% halal.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Curry Fried Chicken',
    contactPhone: '(385) 528-0786',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'habibi-grill',
    title: 'Habibi Grill',
    slug: 'habibi-grill',
    description: 'Mediterranean and Middle Eastern cuisine. Fresh kabobs, hummus, and falafel. Halal certified.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Habibi Grill',
    contactPhone: '(801) 419-0289',
    address: '3460 S Redwood Rd, Ste 5A',
    city: 'West Valley City',
    zipCode: '84119',
    status: 'approved',
    featured: false,
  },
  {
    id: 'ofalafel',
    title: "O'Falafel Etc",
    slug: 'ofalafel-etc',
    description: 'Fresh falafel, shawarma, and Mediterranean classics. Vegetarian-friendly with halal meat options.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: "O'Falafel",
    contactPhone: '(801) 521-5753',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'beirut-cafe',
    title: 'Beirut Cafe',
    slug: 'beirut-cafe',
    description: 'Authentic Lebanese cuisine in the heart of Salt Lake. Halal meats and vegetarian options.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Beirut Cafe',
    contactPhone: '(801) 363-4436',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'kabob-bros',
    title: 'Kabob Bros',
    slug: 'kabob-bros',
    description: 'Fresh grilled kabobs and Mediterranean favorites. Family-owned halal restaurant.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Kabob Bros',
    contactPhone: '(801) 565-9300',
    city: 'West Jordan',
    status: 'approved',
    featured: false,
  },
  {
    id: 'saffron-valley',
    title: 'Saffron Valley',
    slug: 'saffron-valley',
    description: 'Award-winning Indian restaurant with multiple Utah locations. Curries, kebabs, and biryani. Halal options available.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Saffron Valley',
    contactPhone: '(801) 203-3325',
    city: 'Multiple Locations',
    status: 'approved',
    featured: false,
  },
  {
    id: 'oromian',
    title: 'Oromian Restaurant',
    slug: 'oromian-restaurant',
    description: 'Authentic Ethiopian cuisine formerly known as African Restaurant. Traditional injera with various meat and vegetarian stews.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Oromian Restaurant',
    contactPhone: '(801) 906-8264',
    address: '1522 S State St',
    city: 'Salt Lake City',
    zipCode: '84115',
    status: 'approved',
    featured: false,
  },
  {
    id: 'mahider',
    title: 'Mahider Ethiopian Restaurant',
    slug: 'mahider-ethiopian-restaurant',
    description: 'Award-winning Ethiopian restaurant with authentic dishes passed down through generations. Traditional injera, tibs, and honey wine.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Mahider Restaurant',
    contactPhone: '(801) 975-1111',
    address: '1465 S State St',
    city: 'Salt Lake City',
    zipCode: '84115',
    status: 'approved',
    featured: false,
  },
  {
    id: 'afghan-kitchen',
    title: 'Afghan Kitchen',
    slug: 'afghan-kitchen',
    description: 'Authentic Afghan cuisine featuring kabobs, rice dishes, and traditional bread. 100% halal.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Afghan Kitchen',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'zeitoon',
    title: 'Zeitoon Cafe',
    slug: 'zeitoon-cafe',
    description: 'Persian and Mediterranean cuisine. Fresh kebabs, stews, and rice dishes. Halal certified.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Zeitoon Cafe',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'alibaba',
    title: 'Alibaba Restaurant SLC',
    slug: 'alibaba-restaurant-slc',
    description: 'Traditional Middle Eastern and Mediterranean cuisine. Generous portions, halal certified.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Alibaba',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'kohinoor',
    title: 'Kohinoor Indian Restaurant',
    slug: 'kohinoor-indian-restaurant',
    description: 'Indian and Pakistani cuisine with halal meat options. Curries, biryani, and tandoori specialties.',
    categoryName: 'Restaurants & Food',
    listingType: 'service',
    contactName: 'Kohinoor',
    contactPhone: '(801) 226-6666',
    city: 'Orem',
    status: 'approved',
    featured: false,
  },

  // GROCERY & HALAL MEAT
  {
    id: 'halal-meat-market',
    title: 'Halal Meat Market',
    slug: 'halal-meat-market',
    description: 'Fresh halal meat including beef, lamb, goat, and chicken. Competitive prices and friendly service.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'Halal Meat Market',
    contactPhone: '(801) 952-0786',
    address: '2407 S Redwood Rd',
    city: 'Salt Lake City',
    zipCode: '84119',
    status: 'approved',
    featured: false,
  },
  {
    id: 'halal-market',
    title: 'Halal Market',
    slug: 'halal-market',
    description: 'Full-service halal grocery store with fresh meats, spices, and imported goods from the Middle East.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactPhone: '(801) 952-0786',
    address: '2407 S Redwood Rd',
    city: 'West Valley City',
    zipCode: '84119',
    status: 'approved',
    featured: false,
  },
  {
    id: 'abdi-bros',
    title: 'Abdi Bros Market',
    slug: 'abdi-bros-market',
    description: 'Somali and East African grocery store. Fresh halal meats and African specialty items.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'Abdi Bros',
    address: '3505 S Main St',
    city: 'South Salt Lake',
    zipCode: '84115',
    status: 'approved',
    featured: false,
  },
  {
    id: 'safa-halal',
    title: 'Safa Halal Market',
    slug: 'safa-halal-market',
    description: 'Halal groceries, fresh meat, and international foods. Serving the West Valley community.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'Safa Market',
    city: 'West Valley City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'african-star',
    title: 'African Star Market',
    slug: 'african-star-market',
    description: 'African groceries and halal products. Specialty items from East Africa.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'African Star',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'mediterranean-market',
    title: 'Mediterranean Market & Deli',
    slug: 'mediterranean-market-deli',
    description: 'Mediterranean and Middle Eastern groceries. Fresh deli items and imported products.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'Mediterranean Market',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'namaste-nanglo',
    title: 'Namaste Nanglo Groceries',
    slug: 'namaste-nanglo-groceries',
    description: 'South Asian grocery store with halal meats and specialty spices.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'Namaste Nanglo',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'shaku-maku',
    title: 'Shaku Maku Market',
    slug: 'shaku-maku-market',
    description: 'Middle Eastern market with fresh halal meats, groceries, and prepared foods.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'Shaku Maku',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'apna-bazaar',
    title: 'Apna Bazaar',
    slug: 'apna-bazaar',
    description: 'Indian and Pakistani grocery store. Halal meats, spices, and imported goods.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'Apna Bazaar',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'qaderi-sweetz',
    title: 'Qaderi Sweetz',
    slug: 'qaderi-sweetz',
    description: 'Afghan and Middle Eastern sweets and pastries. Perfect for celebrations and gifts.',
    categoryName: 'Grocery & Halal Meat',
    listingType: 'product',
    contactName: 'Qaderi Sweetz',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },

  // SERVICES
  {
    id: 'funeral-services',
    title: 'Muslim Funeral Services Utah',
    slug: 'muslim-funeral-services-utah',
    description: 'Islamic funeral and burial services according to Shariah. Compassionate care for families.',
    categoryName: 'Services',
    listingType: 'service',
    contactName: 'Islamic Funeral Services',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'quran-academy',
    title: 'Quran Academy Utah',
    slug: 'quran-academy-utah',
    description: 'Online and in-person Quran classes for all ages. Tajweed, memorization, and Arabic language.',
    categoryName: 'Education & Tutoring',
    listingType: 'service',
    contactName: 'Quran Academy',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'halal-finance',
    title: 'Halal Financial Consulting',
    slug: 'halal-financial-consulting',
    description: 'Islamic finance consulting. Shariah-compliant investments, mortgages, and business financing.',
    categoryName: 'Professional Services',
    listingType: 'service',
    contactName: 'Islamic Finance',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
  {
    id: 'muslim-realtor',
    title: 'Muslim Real Estate Agent',
    slug: 'muslim-real-estate-agent',
    description: 'Helping Muslim families find their dream home. Knowledgeable about halal financing options.',
    categoryName: 'Real Estate',
    listingType: 'service',
    contactName: 'Muslim Realtor',
    city: 'Salt Lake City',
    status: 'approved',
    featured: false,
  },
];
